/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IuEscritorio;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Comision;
import logica.Factura;
import logica.Producto;
import logica.Proveedor;
import static utilidades.DateUtils.formatDate;

/**
 *
 * @author ecoitino
 */
public class ComisionesProveedor extends javax.swing.JDialog {
    
    ArrayList<Comision> comisiones;    
    /**
     * Creates new form ComisionesProveedor
     */
    public ComisionesProveedor(java.awt.Frame parent, boolean modal, ArrayList<Comision> comisiones) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setSize(new Dimension(1000, 600));
        cargarComisiones(comisiones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDataComisiones = new javax.swing.JList();
        verItems = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalComisiones = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Comisiones");

        jScrollPane1.setViewportView(listaDataComisiones);

        verItems.setText("Ver items");
        verItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verItemsActionPerformed(evt);
            }
        });

        jLabel2.setText("Total a Pagar:");

        totalComisiones.setEditable(false);
        totalComisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalComisionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(664, 734, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verItems)))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(verItems)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalComisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalComisionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalComisionesActionPerformed

    private void verItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verItemsActionPerformed
        int posicion = listaDataComisiones.getSelectedIndex();
        if(posicion != -1) {
            Comision comisionSeleccionada = comisiones.get(posicion);;
            if(comisionSeleccionada.tieneFacturas()) {
                new InformacionItems(null, false, comisionSeleccionada).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No hay ventas.");
            } 
        }       
    }//GEN-LAST:event_verItemsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaDataComisiones;
    private javax.swing.JTextField totalComisiones;
    private javax.swing.JButton verItems;
    // End of variables declaration//GEN-END:variables
    private void cargarComisiones(ArrayList<Comision> comisiones) {
        this.comisiones = comisiones;
        listaDataComisiones.setListData(dibujarComisiones(comisiones));
    }

    private Object[] dibujarComisiones(ArrayList<Comision> comisiones) {
        ArrayList<String> listadoComisiones = new ArrayList();
        if(comisiones != null) {
            comisiones.forEach(comision -> {
                Producto producto = comision.getProducto();
                listadoComisiones.add(
                    "Nombre: " + comision.getNombre() +
                    " | Fecha : " + formatDate(comision.getFechaCreacion()) +
                    " | Producto: " + producto.getNombre() +
                    " | Precio: $ " + producto.getPrecio() +
                    " | Unidades vendidas: " + comision.getCantidadUnidadesVendidas() +
                    " | Porcentaje a pagar: % " + comision.getPorcentaje() +
                    " | Total a pagar: $ " + comision.getTotalAPagarPorComision()
                );
                totalComisiones.setText(Float.toString(producto.getProveedor().getTotalAPagar()));                
            });
        }
        return listadoComisiones.toArray();
    }
}
