
package IuEscritorio;

import IuConsola.IuConsola;
import java.awt.Dimension;
import logica.DatosPrueba;
import logica.Fachada;


public class IUGraficaMenu extends javax.swing.JFrame {

    Fachada logica = Fachada.getInstancia();
    
    public IUGraficaMenu() {
       initComponents();
       setSize(new Dimension(1200, 800));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        barraMenu = new javax.swing.JMenuBar();
        menuCrearComision = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        menuAltaComision = new javax.swing.JMenuItem();
        menuConsultarComisiones = new javax.swing.JMenuItem();
        menuGestionFacturas = new javax.swing.JMenu();
        menuAltaFactura = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obligatorio 1");

        menuCrearComision.setText("Inicio");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuCrearComision.add(menuSalir);

        menuAltaComision.setText("Crear comsión");
        menuAltaComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltaComisionActionPerformed(evt);
            }
        });
        menuCrearComision.add(menuAltaComision);

        menuConsultarComisiones.setText("Consultar comisiones");
        menuConsultarComisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarComisionesActionPerformed(evt);
            }
        });
        menuCrearComision.add(menuConsultarComisiones);

        barraMenu.add(menuCrearComision);

        menuGestionFacturas.setText("GestionFacturas");

        menuAltaFactura.setText("Alta de factura por consola (solo para su uso a nivel de testing)");
        menuAltaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltaFacturaActionPerformed(evt);
            }
        });
        menuGestionFacturas.add(menuAltaFactura);

        barraMenu.add(menuGestionFacturas);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuAltaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltaFacturaActionPerformed
        IuConsola consola = new IuConsola();
        consola.nuevoFactura();
    }//GEN-LAST:event_menuAltaFacturaActionPerformed

    private void menuAltaComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltaComisionActionPerformed
        new CrearComision(null,false).setVisible(true);
    }//GEN-LAST:event_menuAltaComisionActionPerformed

    private void menuConsultarComisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarComisionesActionPerformed
        new ConsultarComisiones(null,false).setVisible(true);
    }//GEN-LAST:event_menuConsultarComisionesActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuAltaComision;
    private javax.swing.JMenuItem menuAltaFactura;
    private javax.swing.JMenuItem menuConsultarComisiones;
    private javax.swing.JMenu menuCrearComision;
    private javax.swing.JMenu menuGestionFacturas;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
