
package IuEscritorio;

import IuConsola.IuConsola;
import logica.DatosPrueba;
import logica.Fachada;


public class IUGraficaMenu extends javax.swing.JFrame {

    Fachada logica = Fachada.getInstancia();
    
    public IUGraficaMenu() {
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        barraMenu = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        menuGestionFacturas = new javax.swing.JMenu();
        mnuAltaFactura = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obligatorio 1");

        menuInicio.setText("Inicio");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        menuInicio.add(mnuSalir);

        barraMenu.add(menuInicio);

        menuGestionFacturas.setText("GestionFacturas");

        mnuAltaFactura.setText("Alta de factura por consola (solo para su uso a nivel de testing)");
        mnuAltaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaFacturaActionPerformed(evt);
            }
        });
        menuGestionFacturas.add(mnuAltaFactura);

        barraMenu.add(menuGestionFacturas);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuAltaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaFacturaActionPerformed
        IuConsola consola = new IuConsola();
        consola.nuevoFactura();
    }//GEN-LAST:event_mnuAltaFacturaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menuGestionFacturas;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenuItem mnuAltaFactura;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
